openapi: "3.1.0"
info:
  title: API Customer
  version: "1.0"
servers:
  - url: https://localhost:8080
tags:
  - name: Customer
    description: Customer specific data.
paths:
  /customers:
    post:
      tags:
        - Customer
      summary: Create Customer
      operationId: createCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: OK
    get:
      tags:
        - Customer
      summary: Get all customers
      operationId: getCustomers
      responses:
        '200':
          description: A list of all customers
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerFullData'
        '404':
          description: NOT FOUND
  /customers/{customerId}:
    get:
      tags:
        - Customer
      summary: Retrieve Customer
      operationId: getCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/CustomerFullData'
        '404':
          description: NOT FOUND
  /orders:
    post:
      tags:
        - Order
      summary: Create Order
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: OK
  /orders/{orderId}:
    get:
      tags:
        - Order
      summary: Retrieve Order
      operationId: getOrder
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/OrderFullData'
        '404':
          description: NOT FOUND
  /orders/customers/{customerId}:
    get:
      tags:
        - Order
      summary: Retrieve Order of Customer
      operationId: getOrdersOfCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  type: integer
                  format: int64
        '404':
          description: NOT FOUND
  /articles:
    post:
      tags:
        - Article
      summary: Create Article
      operationId: createArticle
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
      responses:
        '200':
          description: OK
components:
  schemas:
    Customer:
      type: object
      properties:
        firstName:
          type: string
          description: First name of the customer
        lastName:
          type: string
          description: Last name of the customer
        street:
          type: string
          description: Street of the customer
        city:
          type: string
          description: City of the customer
        country:
          type: string
          description: Country of the customer
    CustomerFullData:
      allOf:
        - $ref: '#/components/schemas/Customer'
        - type: object
          properties:
            customerId:
              type: integer
              description: The ID of the customer
              format: int64
      description: Full data of the customer.
    Order:
      type: object
      properties:
        customerId:
          type: integer
          description: The ID of the customer
        articles:
          type: array
          items:
            $ref: '#/components/schemas/OrderArticle'
    OrderFullData:
      allOf:
        - $ref: '#/components/schemas/Order'
        - type: object
          properties:
            orderId:
              type: integer
              description: The ID of the order
              format: int64
      description: Full data of the order.
    OrderArticle:
      type: object
      properties:
        articleId:
          type: integer
          description: The ID of the article
        number:
          type: integer
          description: The number of articles to order
    Article:
      type: object
      properties:
        articleId:
          type: integer
          description: The ID of the article
        name:
          type: string
          description: The name of the article